sudo: required
dist: trusty
env:
  global:
  - PROJECT_NAME=anaconda
  - ORG=rockstat
  - IMAGE_NAME=$ORG/$PROJECT_NAME
  - secure: q2EqlZ1enGJIIxqtjvQzixk1m+5ZyT/EPo7DJlcj+K6hrZfa7rMCF7UGiGnVHirwyvJ3V0/cjIzdRDkPK4WWj40HvKfuroMMJibBnugF5oMONvexMHkKUphKfHqnmjRPwi7otpbr/u1fkJyo3u9r7gHIOls8csqr/Asb2BU3lEjuQJKCoeT8RJD3gqPJIKl5b9rp7MqzhJPjM7XKgKzcPc2gWB0LukrlIBf95J8IcrTuPsFz0i/TkjCpF1cEX/HmF1cNtmeedtYA2veJPpERtdryA7dqa5hhI4RJBofl64lCfb8JE5TTrYs3TqIkKT1r7gD7Zt+rjWTAZqhkGTl3PVZJg9qVubCnsSh6D2r+MDjkcUxorgPbj7mrja0b8HXvXRrWZGLTIlFMWrRNRjtvI0r9QrFhAWoTpOb4LfAHUkkMqGKtZYBJt/4sFGOOXbgjHglOCp8DKeCUCIRr3uS5Bq2mrR1OTYmq0Z9HcI4zCyjhX2eOAnllmptIjfghKmZurhLK/9wMn7xSAFuLvvfSbt7oO2tzYnQ1cok5K0pvPKRaFSYXmVKWAGn1peeWPfK8zVYjtR0KQfOT4hJ30XtnXx0aaVkrowaI8Una8a92eYeCRtFbsunsQMJwk+dJcXXTDc3XXovFKFwszAqGvFs6rRHVmbu3RvXmzQDoK2fBv7Q=
services:
- docker
script:
- docker build -t "${PROJECT_NAME}" .
- docker build -t "${PROJECT_NAME}-lab" -f Dockerfile.lab .
after_script:
- docker images
before_deploy:
- docker tag "${PROJECT_NAME}" "${IMAGE_NAME}:latest"
- docker tag "${PROJECT_NAME}-lab" "${IMAGE_NAME}:lab"
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
deploy:
  provider: script
  skip_cleanup: true
  script:
  - docker push "${IMAGE_NAME}:latest"
  - docker push "${IMAGE_NAME}:lab"
  on:
    branch: master
