#!/bin/bash

chown -R 472:472 /opt/notebooks

/opt/conda/bin/jupyter notebook --notebook-dir=/opt/notebooks \
    --ip='0.0.0.0' \
    --port=8080 \
    --no-browser \
    --allow-root \
    --NotebookApp.token='' \
    --NotebookApp.allow_origin='*'
